# Generated by Django 5.0.3 on 2024-04-01 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='e_mail',
        ),
    ]
